# Generated by Django 2.0 on 2018-09-26 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortener', '0003_auto_20180924_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShortUrlAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortUrl', models.CharField(max_length=100, unique=True)),
                ('longUrl', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='shorturlguest',
            name='shortUrl',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='shorturl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.ShortUrlAuth'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
