# Generated by Django 2.0 on 2018-09-26 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20180926_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='shorturl',
        ),
        migrations.AddField(
            model_name='shorturlauth',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shortener.Profile'),
        ),
    ]
