# Generated by Django 2.1.1 on 2018-09-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0009_auto_20180928_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturlauth',
            name='author',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
